server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

# Database settings.
database:
    driverClass: com.mysql.jdbc.Driver
    user: panallyadmin
    password: Panally090117
    url: jdbc:mysql://panally.cinqufhfwblf.ap-south-1.rds.amazonaws.com/test