server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

# Database settings.
database:
    driverClass: com.mysql.jdbc.Driver
    user: test
    password: test
    url: jdbc:mysql://localhost:3306/test
